### PR TITLE
Pull XML Changes into Master

### PR DESCRIPTION
**Pull request by sabishiangel**
Please review the code to make sure my changes are acceptable. Changes were made in the Login Acvitity page and the following were added:
- login pin page
- admin page
- currency page

Intent paths were also changed to match the wireframe flow chart.

### CODE REVIEW

**Comment by BrettMatthews** [comment]
As I understand it Ashley you're requesting a review of the code. This is not something I can do. Paul can respond to you. Paul, would you like me to invite Floyd in at this point, or shall we wait?


________________________________

**Comment by BrettMatthews** [comment]
As I understand it Ashley you're requesting a review of the code. This is not something I can do. Paul can respond to you. Paul, would you like me to invite Floyd in at this point, or shall we wait?

**Comment by pauljathome** [comment]
Others are certainly willing to comment but I strongly suspect I'm the most
qualified person to review this.

Ashley - should do this today.

**Comment by pauljathome** [comment]
Merged into master

**Pull request merged**
